### ISSUE TITLE
I created a personal python file based on the readme, and the bug after running is that the remote host denied access, am I missing any steps?

### ISSUE THREAD

**Issue by Lhanmao** [SocAIty/py_audio2face#3]
API http://localhost:8011/status call error: HTTPConnectionPool(host='localhost', port=8011): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A51CA7D190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by w4hns1nn** [comment]
Please check the following:
1. Is nvidia audio2face installed.
2. Check the install path
3. If you run nvidia audio2face in headless mode under which port / adress is it running?

You can then init py_audio2face with your settings
import py_audio2face as pya2f
a2f = pya2f.Audio2Face(
            api_url="Your_URL",  
            a2f_install_path: str = "Your Install Path,
)

Let me know if this solved the issue
