### ISSUE TITLE
[Question] export to .mp4?

### ISSUE THREAD

**Issue by salahzoubi** [SocAIty/py_audio2face#4]
Hello, great work on this project! I'm wondering if there's a way to export an animation directly to .mp4? Or convert the .USD file to mp4? Ideally it would be the animation recorded with the face pose in neutral facing the camera. 

Thanks!

**Comment by w4hns1nn** [comment]
Hi salahzoubi, a direct way does not yet exist.

What you can do is to use the animation in UE5 with your metahuman character and then render a movie scene right in unreal engine. This gives you the mp4 you are looking for.
