### ISSUE TITLE
Settings.py documentation

### ISSUE THREAD

**Issue by yiouyou** [SocAIty/py_audio2face#5]
For a newbie of audio2face, have no idea about how to set the settings.py.

How to customize the following settings? Where to find the necessary information, asseuming that the audio2face has been installed successfully.
```
DEFAULT_PLAYER_INSTANCE = "/World/audio2face/Player"
DEFAULT_SOLVER_INSTANCE = "/World/audio2face/BlendshapeSolve"
DEFAULT_A2E_INSTANCE = "/World/audio2face/CoreFullface"

DEFAULT_AUDIO_STREAM_PLAYER_INSTANCE = "/World/audio2face/PlayerStreaming"
```

**Comment by w4hns1nn** [comment]
Hi yiouyou,

py_audio2face comes with the "mark_arkit_solved_default.usd" and "mark_arkit_solved_streaming.usd" file. We load this scene into audio2face. In this scene, the objects are structured in this way.
You would need to adjust the settings if for example you rename the components in audio2face or you want to use py_audio2face with your own characters.

Does this help?
