### ISSUE TITLE
[Need help for running the codes ><]

### ISSUE THREAD

**Issue by differe94nt** [SocAIty/py_audio2face#6]
Thank you for your awesome works!!!
I am new to Audio2Face!><
I have 2 questions. 
1. I have tried the following code:
`a2f.audio2face_single(
   audio_file_path="path/to/audio/file.wav", #  path of the audio file you want to animate
   output_path="path/to/output/animation.usd",  # path where the animation file will be saved
   fps=60, # frames per second for the animation. Higher fps will result in smoother animations and longer processing time
   emotion_auto_detect=True  # automatically detect emotions in the audio file. If false the set emotion will be used
)`
I got an USD file, but I am unsure what I should do as the following steps. 
2. 
I have tried your test_simply.py
I can hear the audio I have fed into, but there is no character showing up. 
Could you please provide some hints? I am new to Audio2Face!><
`

> [Running] python -u "c:\Users\am\py_2face\py_audio2face\tests\test_simple.py"
> C:\Users\am\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
>   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
> Installed versions:  ['audio2face-2023.2.0']
> Using version:  audio2face-2023.2.0
> audio2face running
> load scene C:\Users\am\AppData\Local\Programs\Python\Python310\lib\site-packages\py_audio2face\assets\mark_arkit_solved_default.usd
> audio2face running
> load scene C:\Users\am\AppData\Local\Programs\Python\Python310\lib\site-packages\py_audio2face\assets\mark_arkit_solved_streaming.usd
> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> I0000 00:00:1721466500.534810   21672 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_client, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
> 
> [Done] exited with code=0 in 286.425 seconds

`

I hope you can provide some hints or resources for me to follow!
I deeply appreciate your works!!!😊
![image](https://github.com/user-attachments/assets/49428d57-9c2e-4098-9bdd-e2e38f4e82df)

![image](https://github.com/user-attachments/assets/54ae0ebd-53a8-43b7-98b5-d5e874522fd8)

**Comment by w4hns1nn** [comment]
Hi, 
as shown in the image, the scene was loaded correctly. What type of GPU do you have? 
Audio2Face needs a GPU of the RTX family.

**Comment by differe94nt** [comment]
Thank!!! It works after we use the computer with RTX GPU!
But, we have another issue here. 
Instead of loading the default Mark, where can we load the talking head customized by us? We are unsure in which file we can find the path to load our own usd.
Thank you!!!!

**Comment by w4hns1nn** [comment]
In UE5 you'll need to link the bones to your Metahuman. [JSFILMZ ](https://www.youtube.com/@Jsfilmz)has some tutorials about that.
Maybe I'll make a follow-up video to explain this also, or to provide a script to also load this automatically intu UE5.
