### ISSUE TITLE
Does the .usd file contains eye and head movements?

### ISSUE THREAD

**Issue by yiouyou** [SocAIty/py_audio2face#7]
Any way to export the eye and head movements out of a2f by python?

Thanks,
Zack

**Comment by w4hns1nn** [comment]
Yes, the file contains this information and animation
________________________________
From: Zack Song ***@***.***>
Sent: Friday, July 26, 2024 8:58:01 AM
To: SocAIty/py_audio2face ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SocAIty/py_audio2face] Does the .usd file contains eye and head movements? (Issue #7)


Any way to export the eye and head movements out of a2f by python?

Thanks,
Zack
